### ISSUE TITLE
"Load my notes" loads artifact characters and three blank titled notes

### ISSUE THREAD

**Issue by transiient** [vhexs/UselessJournal#1]
`IO::openJournalFromFile()` loads a created note with the prefix "T" in the title. It also loads a "D" character inside the first blank note.

Content of journal.uj:

```
##T test
##B 23
##D
```

**Comment by vhexs** [comment]
@vhexs Fixing

**Comment by transiient** [comment]
Fixed in [commit 15ef17a](https://github.com/vhexs/UselessJournal/commit/15ef17a844c821f06992f51b1f3e638c1bbf7c8f), closing issue
